// Generated by Website Factory. Update via the factory pipeline, not by hand.

export type WeekdayHours = {
  day: string;
  time: string;
  closed: boolean;
};

export type RestaurantConfig = {
  name: string;
  shortName: string;
  tagline: string;
  logoGlyph: string;
  cuisine: string;
  website?: string;
  priceRange?: string;
  coordinates?: {
    latitude: number;
    longitude: number;
  };
  nativeTagline: string;
  nativeTaglineTranslation: string;
  phone: string;
  phoneLink: string;
  landlinePhone?: string;
  landlinePhoneLink?: string;
  email: string;
  address: {
    street: string;
    cityLine: string;
    city: string;
  };
  mapsUrl: string;
  googleBusinessProfileUrl: string;
  socialMedia: {
    instagram: string;
    facebook: string;
    tiktok: string;
    hidden: {
      instagram: boolean;
      facebook: boolean;
      tiktok: boolean;
    };
    titleHidden: boolean;
  };
  closedDays: number[];
  closedDaysLabel: string;
  hours: WeekdayHours[];
  reservationTimeSlots: {
    startHour: number;
    endHour: number;
    stepMinutes: number;
    latestMinutes: number;
  };
  seo: {
    title: string;
    description: string;
    keywords: string[];
    ogTitle: string;
    ogDescription: string;
    locale: string;
  };
  legal: {
    ownerName: string;
    vatId: string;
    responsiblePerson: string;
  };
};

export const restaurant: RestaurantConfig = {
  "name": "Noli Café",
  "shortName": "Noli Café",
  "tagline": "Cafe",
  "logoGlyph": "N",
  "cuisine": "Cafe",
  "nativeTagline": "",
  "nativeTaglineTranslation": "",
  "phone": "ig",
  "phoneLink": "",
  "email": "",
  "address": {
    "street": "Ebertstraße 38",
    "cityLine": "70806 Kornwestheim",
    "city": "Kornwestheim"
  },
  "mapsUrl": "https://maps.google.com/?cid=6608758776759404685&g_mp=CiVnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLkdldFBsYWNlEAIYBCAA",
  "googleBusinessProfileUrl": "https://maps.google.com/?cid=6608758776759404685&g_mp=CiVnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLkdldFBsYWNlEAIYBCAA",
  "socialMedia": {
    "instagram": "https://www.instagram.com/nolicafecart/",
    "facebook": "https://www.facebook.com/p/NOLI-cafe-bar-100063675095458",
    "tiktok": "https://tiktok.com/@nolicafe.kornwestheim",
    "hidden": {
      "instagram": false,
      "facebook": false,
      "tiktok": true
    },
    "titleHidden": false
  },
  "closedDays": [
    1,
    3
  ],
  "closedDaysLabel": "Geschlossen: Montag, Mittwoch.",
  "hours": [
    {
      "day": "Montag & Mittwoch",
      "time": "Geschlossen",
      "closed": true
    },
    {
      "day": "Dienstag, Donnerstag & Freitag",
      "time": "08:30–13:00 Uhr",
      "closed": false
    },
    {
      "day": "Samstag",
      "time": "09:00–16:00 Uhr",
      "closed": false
    },
    {
      "day": "Sonntag",
      "time": "09:00–13:00 Uhr",
      "closed": false
    }
  ],
  "reservationTimeSlots": {
    "startHour": 17,
    "endHour": 21,
    "stepMinutes": 30,
    "latestMinutes": 30
  },
  "seo": {
    "title": "Noli Café | Cafe in Kornwestheim",
    "description": "Noli Café in Kornwestheim. cafe Küche, aktuelle Öffnungszeiten und Kontaktinformationen auf einen Blick.",
    "keywords": [
      "Noli Café",
      "Cafe Kornwestheim",
      "Noli Café Kornwestheim"
    ],
    "ogTitle": "Noli Café",
    "ogDescription": "Noli Café in Kornwestheim. cafe Küche, aktuelle Öffnungszeiten und Kontaktinformationen auf einen Blick.",
    "locale": "de_DE"
  },
  "legal": {
    "ownerName": "",
    "vatId": "",
    "responsiblePerson": ""
  }
};

export function isClosedDay(dateStr: string): boolean {
  if (!dateStr) return false;
  const day = new Date(dateStr).getDay();
  return restaurant.closedDays.includes(day);
}

export function generateTimeSlots(): string[] {
  const startHour: number = restaurant.reservationTimeSlots.startHour;
  const endHour: number = restaurant.reservationTimeSlots.endHour;
  const stepMinutes: number = restaurant.reservationTimeSlots.stepMinutes;
  const latestMinutes: number = restaurant.reservationTimeSlots.latestMinutes;
  const slots: string[] = [];
  for (let hour = startHour; hour <= endHour; hour++) {
    for (let minute = 0; minute < 60; minute += stepMinutes) {
      if (hour === endHour && minute > latestMinutes) break;
      const hh = hour.toString().padStart(2, "0");
      const mm = minute.toString().padStart(2, "0");
      slots.push(`${hh}:${mm}`);
    }
  }
  return slots;
}
