// Generated by Website Factory. Update via the factory pipeline, not by hand.

export type Review = {
  author: string;
  rating: number;
  text: string;
  time: string;
};

export type ReviewsData = {
  overallRating: number;
  totalRatings: number;
  reviews: Review[];
};

export const reviewsDataGeneratedFromFactory = true;

export const reviewsData: ReviewsData = {
  "overallRating": 5,
  "totalRatings": 16,
  "reviews": [
    {
      "author": "Katja Weichsel",
      "rating": 5,
      "text": "Das Konzept des Café Noli ist überraschend einfach und setzt einen Höhepunkt in den Alltag. Ein hübscher Caféstand unter dem Magnolienbaum eines denkmalgeschützten Arbeiterhäuschens ist der Hingucker der ruhigen Straße, nur wenige Gehminuten vom Bahnhof entfernt. Mehrmals die Woche hat es geöffnet, und durch das Betätigen einer Klingel erscheinen die sympathischen Cafébetreiber. Der Kaffee ist delikat, und auch nicht-Kaffee-Trinker kommen mit einem leckeren Kakao oder Matcha auf ihre Kosten. Ein netter Treff für nette Menschen! Definitiv eines meiner Lieblingscafés!",
      "time": "in der letzten Woche"
    },
    {
      "author": "Joseph S.",
      "rating": 5,
      "text": "Das Noli Café wird von einer total sympathischen jungen Familie betrieben. Sie verkaufen Coffee to Go direkt vor der Haustür. Der Kaffee-Wagen ist echt cool und die verschiedenen Getränke super lecker. Seit heute gibt’s auch Iced Getränke 🤩 - natürlich gibt’s alles auch mit Hafermilch 🌱",
      "time": "vor 3 Wochen"
    },
    {
      "author": "Jerome Greenhalgh",
      "rating": 5,
      "text": "Wie ein Kaffee bei den Nachbarn, Persönlich, lecker und einfach! Und noch Croissants von Bäckerei Dannemann runden das Angebot ab! Klasse.",
      "time": "vor einem Monat"
    },
    {
      "author": "Axel K.",
      "rating": 5,
      "text": "Super leckerer Hafer Cappuccino… Danke",
      "time": "vor einem Monat"
    },
    {
      "author": "Mary",
      "rating": 5,
      "text": "Der kleine orangefarbene Kaffee-Stand „Noli“ unter dem Magnolienbaum ist einfach zauberhaft ☕🌸\nSo unscheinbar und doch etwas ganz Besonderes. Der Cappuccino war fantastisch – mit viel Liebe gemacht und perfekt für einen kleinen Genussmoment unterwegs. Eine richtig schöne Idee, die den Tag ein bisschen schöner macht. Ich komme auf jeden Fall wieder 💛",
      "time": "vor einem Monat"
    }
  ]
};
